# Generated by Django 4.2.23 on 2025-08-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('population', models.BigIntegerField()),
                ('yearly_change', models.FloatField()),
                ('net_change', models.IntegerField()),
                ('density', models.FloatField()),
                ('land_area', models.FloatField()),
                ('migrants', models.IntegerField()),
                ('fertility_rate', models.FloatField()),
                ('median_age', models.FloatField()),
                ('urban_pop_percent', models.FloatField()),
                ('world_share', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('water_consumption', models.FloatField()),
                ('energy_consumption', models.FloatField()),
                ('food_production_index', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'unique_together': {('country', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PopulationTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'unique_together': {('country', 'year')},
            },
        ),
    ]
