# Generated by Django 4.2.23 on 2025-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='populationtrend',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='populationtrend',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='resourceconsumption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourceconsumption',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='PopulationTrend',
        ),
        migrations.DeleteModel(
            name='ResourceConsumption',
        ),
    ]
