# Generated by Django 4.2.23 on 2025-08-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ChatConversation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
