[build]
  publish = "dist"  # or your build folder
  command = "npm run build"


[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "https://bonengmalakas.netlify.app/*"
  to = "https://bonengmalakas.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  [headers."/*"]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"